// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// FitBreakPoints
IntegerVector FitBreakPoints(StringVector references, NumericMatrix values, double lambda, StringVector method);
RcppExport SEXP _proteoformR_FitBreakPoints(SEXP referencesSEXP, SEXP valuesSEXP, SEXP lambdaSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type references(referencesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< StringVector >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(FitBreakPoints(references, values, lambda, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_proteoformR_FitBreakPoints", (DL_FUNC) &_proteoformR_FitBreakPoints, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_proteoformR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
