# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FitBreakPoints <- function(references, positions, values, lambda, method = "constant") {
    .Call(`_proteoformR_FitBreakPoints`, references, positions, values, lambda, method)
}

