# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DetectBreakpoints <- function(values, lambda, model_type) {
    .Call(`_proteoformR_DetectBreakpoints`, values, lambda, model_type)
}

FitModel <- function(values, breakpoints) {
    .Call(`_proteoformR_FitModel`, values, breakpoints)
}

test_ObjectiveCalculator <- function() {
    .Call(`_proteoformR_test_ObjectiveCalculator`)
}

